services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: portofolioo_front
    ports:
      - "3000:80"
    restart: unless-stopped
    volumes:
      - ./front:/usr/share/nginx/html:ro
